services:
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: toggl_user
      POSTGRES_PASSWORD: toggl_password
      POSTGRES_DB: toggl_card_games
  
  card-games-api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_TYPE: "postgres"
      DB_URL: "host=postgres user=toggl_user password=toggl_password dbname=toggl_card_games port=5432"
      BIND_PORT: 8080
    command: ["./card-games-api"]